name: Mangas Noty

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # o como lo tengas

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright (Chromium)
        run: |
          python -m playwright install --with-deps chromium

      - name: Run checker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          FETCH_BACKEND: playwright          # -> usa httpx; cae a Playwright en 403/5xx
          HTTP_TIMEOUT: "30"
          HTTP_RETRIES: "1"
          HTTP_BACKOFF: "1.0"
        run: |
          python main.py

      - name: Commit updated series.yaml (si cambió)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain series.yaml)" ]]; then
            git add series.yaml
            git commit -m "chore: update last_chapter [skip ci]"
            git push origin HEAD:${GITHUB_REF_NAME}
          else
            echo "Sin cambios en series.yaml"
          fi
