name: manga-watcher

on:
  schedule:
    - cron: "*/15 * * * *"   # cada 15 minutos
  workflow_dispatch:
  push:
    paths:
      - "**.py"
      - "series.yaml"
      - ".github/workflows/watcher.yml"
      - "requirements.txt"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python main.py

      - name: Commit updated series.yaml (si cambió)
        run: |
          if [[ -n "$(git status --porcelain series.yaml)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add series.yaml
            git commit -m "chore: update last_chapter [skip ci]"
            git push
          fi
